name: 'Publish e-Report'
on:
  push:
    branches:
      - main

jobs:
  publish-eReport:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Melakukan setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Melakukan instalasi rust stable channel
        uses: dtolnay/rust-toolchain@stable
      - name: Melakukan instalasi dependencies untuk rust (untuk ubuntu)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Melakukan instalasi frontend React Typescript
        run: npm install
      - name: Set rahasia.rs
        env: 
           KONTEN_RAHASIA_RS: ${{ secrets.KONTEN_RAHASIA_RS }}
        run: |
           echo "Current Directory $(pwd)"
           echo $KONTEN_RAHASIA_RS >> src-tauri/src/fungsi/rahasia.rs
           if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
             # Ganti forward slas dengan backslash untuk windows
             sed -i 's/\//\\/g' src-tauri/src/fungsi/rahasia.rs
           fi
           ls -l src-tauri/src/fungsi/rahasia.rs
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: e-Report-v__VERSION__
          releaseName: 'e-Report v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
